name: yt-dlp to Google Drive

on:
  repository_dispatch:
    types: [run-yt-dlp]

jobs:
  ytdlp_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yt-dlp google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run yt-dlp and Upload
        env:
          VIDEO_URL: ${{ github.event.client_payload.url }}
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python run_ytdlp.py
